# .github/workflows/generate_full_commit_report.yml
name: Generate Full Commit Report

on:
  workflow_dispatch: # Enables manual trigger from GitHub's Actions tab

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Generate the full commit report
      - name: Generate full commit report
        run: |
          git log --pretty=format:"%H,%an,%ae,%cn,%ce,%ad,%cd,%s,%b" --date=iso > full_commit_report.csv

      # Step 3: Upload the report as an artifact
      - name: Upload full commit report
        uses: actions/upload-artifact@v3
        with:
          name: full_commit_report
          path: full_commit_report.csv
